version: "3.9"
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: ozontestovoe
    ports:
      - "4040"
    volumes:
      - pgdata:/var/lib/postgresql/data
  graphql-service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
          - postgres
volumes:
  pgdata:
